### ISSUE TITLE
Demo club for test

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#100]
I suggest we set up a demo account new (potential) users can use to try out the app. Could be something like:   demo@tranarappen.se  

Comments?

**Comment by jonkri** [comment]
Perhaps it would suffice to simply create such a test account and give it access to the club that is configured now?

**Comment by jonkri** [comment]
Also, please assign either the "optional for 1.0" label or 1.0 milestone for this issue. :)

**Comment by jonkri** [comment]
I mean, I think it makes sense to wait with configuring a separate instance before a need for it arises.

**Comment by jonkri** [comment]
We decided to rename the current instance to "Demo IK" (in the database), and extend the Android and web applications to fetch the instance/club name from the user-info endpoint.

**Comment by jonkri** [comment]
The user demo@tranarappen.se now has access to the instance, which name now is "Demo IK".

**Comment by jonkri** [comment]
The club name is now visible in the top-left of the web application.

@hesa: When the club name is displayed in the Android application (assuming you think it should be), please close this issue.

**Comment by hesa** [comment]
The club name is now shown in the Android app (in the Club information view which the user can choose from an options menu).

**Comment by jonkri** [comment]
Nice!
