### ISSUE TITLE
Odd upload behaviour

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#101]
Background: @jonkri and i (@hesa) chatted over phone and had some trouble with uploading files. This issue is used to track down the (last?) issue/bug before 1.0

Create Video:
---------------------
  "8e0d5e2c-03f6-4a31-b6e9-d059c4900b7d" ,
  "recorded": "2016-07-29T13:28:36.000000Z" ,
  "memberUuid": "54622361-b2a7-4c4a-857c-e7fc57e1fe09"

==>  uuid: f77b646f-29e2-4e1a-9631-f1d4217d8f2f

Upload video:
---------------------
 https://app.tranarappen.se/api/0.0.0//videos/uuid/f77b646f-29e2-4e1a-9631-f1d4217d8f2f/upload

Uploading of data (the video file) seems to work, but I don't get
response code from the server.

**Comment by hesa** [comment]
Headers I send:

        connection.setRequestProperty("X-Token", LocalStorage.getInstance().getLatestUserToken());
        connection.addRequestProperty("X-Instance", LocalStorage.getInstance().getCurrentClub());

**Comment by jonkri** [comment]
:dancer:

**Comment by hesa** [comment]
Behavior can not be reproduced on app running in (a newly started) emulator. Could it be that the app has some sockets lying around making life hard ... Rebooting phone and retrying to upload.

**Comment by hesa** [comment]
Recorded this: http://www.dailymotion.com/video/x2mlz5d

Upload took forever and ever .... :(

**Comment by hesa** [comment]
Uploading using 3g/4g:   not working well
Uploading using wifi: not working well either

**Comment by hesa** [comment]
Will try on emulator...now the same s%%t happens on the emulator....

**Comment by hesa** [comment]
https://github.com/hesa/CoachAndroidApp/blob/master/app/src/main/java/com/sandklef/coachapp/http/HttpAccess.java

**Comment by hesa** [comment]
Android version on Mobile:       6.0.1
Android version om emulator:   6.0

**Comment by jonkri** [comment]
curl --data-binary @sample.3gp --insecure --request POST https://app.tranarappen.se/api/0.0.0/videos/uuid/$VIDEO_UUID/upload

(Also <code>X-Instance</code> and <code>X-Token</code>.)

**Comment by jonkri** [comment]
curl --data "{ \"recorded\": \"2015-12-29T19:31:12.081528Z\", \"trainingPhaseUuid\": \"bd59ad1d-6c64-4d2b-a5f2-108c8ec5b931\" }" --header "Content-Type: application/json" --request POST https://app.tranarappen.se/0.0.0/videos

**Comment by hesa** [comment]
Ok, stats from a computer at work (really really good network):

Summary:
===========================
  Create
  ---------------------------
  uuid: 68e8d901-23ce-4d6b-89f4-cec7c4354281
  time: 5

  Upload
  ---------------------------
  time: 27


... my network (at our summer house, crappy network??):

Summary:
===========================
  Create
  ---------------------------
  uuid: 09fe84a5-2c94-4ea8-a4c3-59aeeda663f7
  time: 0

  Upload
  ---------------------------
  time: 1

**Comment by hesa** [comment]
[test-upload.tar.gz](https://github.com/hesa/tranarappen/files/390939/test-upload.tar.gz)

**Comment by hesa** [comment]
cat created.json  | sed 's/,/\n/g' | grep uuid | sed 's/\:/ /g' | awk ' { print $2}' | sed -e 's/,//g' -e 's/"//g'

**Comment by hesa** [comment]
Fucking awful code ;)

**Comment by jonkri** [comment]
If something is stupid but works, then it's not stupid.

**Comment by hesa** [comment]
I am not super happy with tele2 (my broadband network provider). Network sucks here - but Netflix/SvtPlay (streamin videos) are ok. 

Arrggrrgrggrgr, will fix timeout and handle error in a proper way.

**Comment by hesa** [comment]
If something is stupid then it is stupid

**Comment by hesa** [comment]
.... finally :)
