### ISSUE TITLE
Context menu for video in TrainingPhase fragmen

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#35]

**Comment by jonkri** [comment]
Would you mind reminding me what we talked about here?

**Comment by hesa** [comment]
When in the traning hall it would be convenient for a coach to be able to watch the latest recorded (or today's recorded) videos for a specific tp.... or something like that.

Not needed for 1.0 I believe.

**Comment by jonkri** [comment]
Hmm... If we are not sure if this should be in 1.0 or not, we could remove the "optional for 1.0" label for now.

**Comment by jonkri** [comment]
Please decide if we should rule it out for 1.0 (and if so, just unassign yourself), or if we want to keep it (in which case you can simply remove the "optional for 1.0" label).

**Comment by jonkri** [comment]
Actually, if it's 1.0, you don't need to do anything, but if it's optional for 1.0, you could switch to "optional for 1.0" and unassign yourself.

**Comment by hesa** [comment]
not needed.
