### ISSUE TITLE
Put information and marketing material on the web site

### ISSUE THREAD

**Issue by jonkri** [hesa/tranarappen#75]
We'll want to put information about the app, including the marketing material (and screenshots), on [http://tränarappen.se/](http://tränarappen.se/). This depends on 0.1, since we will need the screenshots.

**Comment by jonkri** [comment]
@hesa: Could you e-mail me the screenshots, and the photo (if you took one)? Thanks!

**Comment by jonkri** [comment]
@hesa: Ping. :)

**Comment by hesa** [comment]
Pong

See email :)

**Comment by jonkri** [comment]
I'm opening this issue and assigning it to me. I will close it when the web site is online.

**Comment by jonkri** [comment]
@hesa: What do you think of this? https://tränarappen.se/

**Comment by jonkri** [comment]
OK, GitHub doesn't like internationalized domain names.

https://tranarappen.se/

**Comment by jonkri** [comment]
http://tranarappen.se/
