### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#76]
When uploading instruction video I get:

05-29 00:03:45.025 1661-1794/coachassistant.sandklef.com.coachapp D/ServerCode: 413
05-29 00:03:45.025 1661-1794/coachassistant.sandklef.com.coachapp D/serverResponseMessage: Request Entity Too Large
05-29 00:03:45.030 1661-1794/coachassistant.sandklef.com.coachapp E/StorageRemoteWorker:  Failed uploading video to server: Failed to access http

Any ideas?

**Comment by jonkri** [comment]
Adding the 0.1 milestone!

**Comment by jonkri** [comment]
Thank you, @hesa! This is now fixed!

**Comment by hesa** [comment]
07-19 18:28:05.031 24333-24333/coachassistant.sandklef.com.coachapp D/ViewRootImpl: #3 mView = null
07-19 18:28:44.391 24333-26665/coachassistant.sandklef.com.coachapp D/ServerCode: 413
07-19 18:28:44.391 24333-26665/coachassistant.sandklef.com.coachapp D/serverResponseMessage: Request Entity Too Large

**Comment by jonkri** [comment]
OK, I can reproduce this, but I have no idea what's causing it so far. Looking into it!

**Comment by jonkri** [comment]
It seemed to start working when I restarted a service, so I must have made some kind of mistake during deployment. It should work now.
