### ISSUE TITLE
The possibility to remove videos in the web application

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#82]
How do we do when a user wants to remove a team, tp or member?

**Comment by hesa** [comment]
Remove video: ok

Remove tp, member, team: postponed to later ... some fine day

**Comment by jonkri** [comment]
@hesa: Video database entities can now be removed using a remove button under the "Filmklipp" video, or on the single video page. The actual video data is kept - please let me know if you want the file to be removed as well.
