### ISSUE TITLE
Shift orientation on recorded video

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#83]
Based  on the orientation hint as set by the app we should/can change the video orientation to make sure all browsers (and others) can display the video the way the user wants.

**Comment by jonkri** [comment]
Presumably mediainfo or the like should be used on the server to determine this. If so, we can extend the web application to display the video in the right way.

**Comment by jonkri** [comment]
@hesa: When I download member videos displayed with the incorrect orientation and open them with my video player, they still have the wrong orientation, so I'm assuming this is an Android problem.

**Comment by hesa** [comment]
The implementation on the android app has changed a lot since the first recorded video. Can you check if this is true for a late video

**Comment by jonkri** [comment]
@hesa: There is only one video since we sat together at Lindholmen, and I can't determine what the orientation is supposed to be on that video. Could you please upload one horizontal and one vertical video, please?

**Comment by hesa** [comment]
@jonkri: a couple of new ones uploaded. The content of the videos should "pretty much" explain the orientation. Can you check 'em out?

**Comment by jonkri** [comment]
@hesa: I'm assuming that the text in the video was recorded to be displayed horizontally in both portrait and landscape mode. When I open the videos in Totem, the horizontal videos are displayed in this way, but the vertical videos are not. The videos are displayed in the same way in the web application. Based on this, I'm assuming that the Android app is at fault here.

If you want to download an uploaded video you can do this:

    curl -H "Cookie: token=..." https://app.tranarappen.se/api/0.0.0/clubs/f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/44f1f78b-5a84-4abf-8e43-120ae4a12a0d/download > 1.webm

I'm assigning this issue to you. Let me know if there's anything else that I can do.

**Comment by hesa** [comment]
I get:

 <unsupportedRoute/>

when using the curl command above

**Comment by jonkri** [comment]
The URL is outdated, since the last refactoring. Try this:

    curl -H "X-Instance: c1a1501b-f0af-4c2e-b925-a2aad7b61335" -H "Cookie: token=..." https://app.tranarappen.se/api/0.0.0/videos/uuid/d7f92c57-1251-4c7c-b842-fb3cbb0fe53c/download > 1.webm

**Comment by hesa** [comment]
Ok, some hours later ;)

**Recorded on the device**

* Android's video app AND our app records in the same way. That is both use orientation hint, typically found by:
  mediainfo file.mp4 | grep Rotat

* VLC and Totem don't display them correctly (well, one of the file is)

**Downloaded**

* When downloading (using photos.google.com) the file recorded by Android app the video is "flipped". VLC and Totem can display them correctly.

* When download from our app's web interface (using the command above) VLC and Totem CAN NOT display them correctly (apart from  the one which was recorded in the "natural" orientation).

So my suggestion is that we (on the server side) flip the videos using the orientation hints. I can look into this :)

**Comment by hesa** [comment]
@jonkri what tool is converting on the server side?

acvonv, ffmpeg...?

**Comment by jonkri** [comment]
Thanks for this!

Do you mean that the videos won't play correctly in <em>either</em> the web application, VLC or Totem, unless we go ahead and modify the file on the server?

**Comment by hesa** [comment]
yup :(

**Comment by jonkri** [comment]
Ah, then maybe something is wrong with our conversion command.

Here is the command that is being used:

https://github.com/hesa/tranarappen/blob/7fdc2ac1fe05d0a48bee3a14b1414fdbe494f97d/server/source/Main.hs#L69-L72

**Comment by hesa** [comment]
I will play around with this a bit. Weather is rather crappy and kids are not here. 

I'll be back

**Comment by jonkri** [comment]
If you want to play around with the videos in the server container, you can do this on app.tranarappen.se:

    docker exec -it server /bin/bash
    ls videos

**Comment by jonkri** [comment]
The Rotation value is set for the videos in the uploads directory.

**Comment by jonkri** [comment]
Perhaps a switch to FFmpeg would solve the problem?

https://trac.ffmpeg.org/ticket/515#comment:12

**Comment by jonkri** [comment]
But I guess it's cheaper to do this with avconv somehow, if that's possible.

**Comment by hesa** [comment]
avconv has a switch for it, will make a table for you mapping output from mediainfo to avconv settings.

**Comment by hesa** [comment]
Need to double/triple check Android app one more time

**Comment by hesa** [comment]
Samsung ... hrmpfh!!! We have to do without 270 degrees right now* ..... here's the table:

Rotation: avconv option
------------------------------------------
90: -vf "transpose=1"
180: -vf "transpose=1,transpose=1"

*) we can assume that if the rotation is 270 we can use "-vf "transpose=2"

**Comment by jonkri** [comment]
Unfortunately, the functionality is not present in libav 11, which is what we have on the server. I'll keep looking into it.

**Comment by jonkri** [comment]
@hesa: I have now switched from libav to FFmpeg, and re-encoded the uploaded video files. Could you please have a look and see if it's correct?

**Comment by hesa** [comment]
First three videos checked were fine. Will test more tomorrow.

**Comment by hesa** [comment]
Works now :)

**Comment by jonkri** [comment]
Brilliant, thanks!
