### ISSUE TITLE
/clubs gives too much info?

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#84]
https://app.tranarappen.se/api/0.0.0//clubs/

GIves, for me, too much information. The following info would suffice:

{"offset":0,"count":4,"items":[{"uuid":"f9d39cc2-cb7f-4ab0-b31a-5c0355596abe","created":"2016-04-26T22:10:15.77165Z", "name":"AS Roma"}  etc etc etc

That is, I suggest we skip members, and especially videos

**Comment by jonkri** [comment]
@hesa: Could you please remind me what the issue is here, and why you are using the clubs endpoint?

**Comment by jonkri** [comment]
@hesa: Ping! :)

**Comment by jonkri** [comment]
I'm closing this issue, as this endpoint doesn't exist anymore.
