### ISSUE TITLE
Wrap up authentication and authorization

### ISSUE THREAD

**Issue by jonkri** [hesa/tranarappen#91]
We should switch to having one (or perhaps more) user name per club, and that this user name is tied to the given club identifier, which is available when logged in.

A user should not be able to access other clubs.

It should not be possible to change clubs in the web application, but it should be possible to sign out.

**Comment by jonkri** [comment]
This translates well into only allowing one club per instance, and just using the one instance that the given user has access to. This would also solve #11.

This would mean that we can remove "clubs/uuid" part of all URLs, and instead pass the given club ID as an instance header. Access would be denied to any user who doesn't have access to the particular instance, and any logged in user can see what instance he or she has access to by using the user-info endpoint.

**Comment by jonkri** [comment]
@hesa: #91 is now done.

The Android app need the following changes.

First, once you have acquired a token, you need to make the equivalent of the following request in your Java code:

    curl -H "Cookie: token=..." https://app.tranarappen.se/api/user-info

The result of this request will contain a JSON object with an "instances" array field. This field informs the client what instances (clubs) the client has access to; the first (zeroth) element of this array will contain the instance identifier that you should use, in the "id" subfield.

So, for instance, if the output is

    {
        "id": "ce315479-1392-4c48-b35b-ec03e4557992",
        "email": "...",
        "name": "Jon Kristensen",
        "phone": null,
        "instances": [{
            "name": "server",
            "id": "c1a1501b-f0af-4c2e-b925-a2aad7b61335"
        }]
    }

then you will use "c1a1501b-f0af-4c2e-b925-a2aad7b61335", or <code>instances[0].id</code>.

You will need to put this instance identifier in the <code>X-Instance</code> header in every request from now on (along with the <code>X-Token</code> header, which should also be set).

Second, you will need to remove "/club/[uuid]" from the request URLs.

This means that the composite endpoint now resides at /0.0.0/composite, but keep in mind that all other application API endpoints have moved as well. Please note also that the composite endpoint doesn't have "name", "uuid" and "created" fields anymore.

**Comment by hesa** [comment]
What am I doing wrong?

 curl -H "X-Instance: c1a1501b-f0af-4c2e-b925-a2aad7b61335" -H "X-Token: DORZCHQzsK6LuEuMSBjoBF" https://app.tranarappen.se/api/0.0.0/composite

==> <unsupportedRoute/>

**Comment by jonkri** [comment]
Thanks for reporting this bug! It should now be fixed, and a new server version has been deployed.

**Comment by hesa** [comment]
Is it possible for a member to NOT be part of a team. I get this back:



 "members": [
  {
   "uuid": "c7b4babd-12c5-4dcf-a23b-130e02f52ab6",
   "created": "2016-07-17T19:07:08.569808Z",
   "name": "Henrik",
   "teamUuid": "1b5ad118-06f5-460a-a933-6248ad2e04d3"
  },
  {
   "uuid": "4f177eff-e788-4eea-ad72-94889985df65",
   "created": "2016-07-17T19:07:03.274187Z",
   "name": "Jon"
  }
 ],

... when I do:

 curl -H "X-Instance:c1a1501b-f0af-4c2e-b925-a2aad7b61335" -H "X-Token:mid1jhcJq4Z0K0uIuVeLL3" https://app.tranarappen.se/api/0.0.0/composite

**Comment by hesa** [comment]
Sorry about the ping pong war between us :)

**Comment by jonkri** [comment]
No, it's good. :)

It has been possible for members not to be assigned to teams for a long time now, so that's by design. Can you work around it in the Android app?

**Comment by hesa** [comment]
Sure, didn't want to add this feature if it wasn't a feature. Hate adding code to fix problems that should not be there. 

GNU Xnee is full of them :(

**Comment by jonkri** [comment]
Good thinking! :)

**Comment by jonkri** [comment]
I think it's justified to keep it as it is, but let me know if you disagree!

**Comment by hesa** [comment]
seems to  be fixed now :)

**Comment by hesa** [comment]
this works:

curl -H "X-token=...."  -H "X-Instance:c1a1501b-f0af-4c2e-b925-a2aad7b61335"  https://app.tranarappen.se/api/download/c1a1501b-f0af-4c2e-b925-a2aad7b61335/f4523ec5-bc61-4d4b-ad58-5edfc8d2f9fc

**Comment by jonkri** [comment]
That's a special endpoint for the web application. I gave you the "correct" endpoint in the other thread. :)

**Comment by jonkri** [comment]
(The web application can't easily set the right headers when it's streaming the video.)

**Comment by hesa** [comment]
Ah, I sniffed my way to the one above :)

**Comment by jonkri** [comment]
Well done! :D
