### ISSUE TITLE
get connection resp code takes a looong time

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#97]
HttpURLConnection connection ;
....
connection = (HttpURLConnection) url.openConnection();
connection.getResponseCode();

The last call takes "forever" (i e 5-10 seconds). Have you changed anything ... or is it a crappy network connection here? (I am currently at our summer house!)

**Comment by hesa** [comment]
The above was uploading ... Now I get this when downloading:

07-19 23:23:42.411 29776-30112/coachassistant.sandklef.com.coachapp W/System.err: Caused by: java.net.SocketTimeoutException: timeout
07-19 23:23:42.421 29776-30112/coachassistant.sandklef.com.coachapp W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:216)
07-19 23:23:42.421 29776-30112/coachassistant.sandklef.com.coachapp W/System.err:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
07-19 23:23:42.421 29776-30112/coachassistant.sandklef.com.coachapp W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
07-19 23:23:42.421 29776-30112/coachassistant.sandklef.com.coachapp W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)


I can stream video to our summer house so the network is ok

**Comment by jonkri** [comment]
@hesa:

I haven't changed anything that I can see would make a difference here. And nothing is suspicious when I'm making requests now. Perhaps there is a problem with the server.

Is this still happening? Is it happening to all endpoints?

**Comment by jonkri** [comment]
Downloading videos seems to work for me as well.

**Comment by hesa** [comment]
Uploading is still slow. But not sloooooow as yesterday.... odd. 

Will look into this problem tonite.

**Comment by jonkri** [comment]
@hesa: As this is optional for 1.0, I'm unassigning you.

**Comment by hesa** [comment]
closed with 101
